### ISSUE TITLE
Localization or internalization

### ISSUE THREAD

**Issue by albertosantini** [rowanmanning/joblint#46]
What about to add support for other languages?

I suppose the words contained in the rules should be moved to external files and loaded depending on the locales.

**Comment by JonathanMH** [comment]
@rowanmanning: I think this project is beautiful, so I'd love to contribute something to da and de translations.

**Comment by lsmith77** [comment]
would like to revive this topic. did anyone do any steps to support multiple languages?

I guess https://github.com/wooorm/franc could help in automatically detecting the language (though this is a nice to have).

**Comment by lsmith77** [comment]
I now took the simple route of simply passing in the translated rules and I guess there is no sense in complicating this library to add internal support for rule translation
