### ISSUE TITLE
Travel required as a warning/notice

### ISSUE THREAD

**Issue by TravelingTechGuy** [rowanmanning/joblint#67]
While some people wouldn't mind traveling for the job, it definitely affects the quality of life, work-life balance etc. I think we should have a warning, or at least a notice on the subject. Not sure if we should measure the percentage of travel as a measure (also, not sure how to do it easily).

**Comment by numbsafari** [comment]
Kinda new here, but this seems a bit awkward as a thing to flag. Some jobs actually require travel. By flagging it, is it possible that someone would think to take it out, leading to incorrect expectations later on?

Also, some people specifically look for jobs that include travel.

For example, if your job is to perform on-site security evaluations, or perform on-site repairs, or meet face-to-face with customers, shouldn't that be spelled out in the job description?

**Comment by numbsafari** [comment]
Ah ... looking through more of the issues I see now that some people are using this more to filter jobs they are evaluating, rather than for employers wanting to ensure their descriptions aren't unintentionally "bad".
