### ISSUE TITLE
What is wrong with a "performance-based" job?

### ISSUE THREAD

**Issue by NickHeiner** [rowanmanning/joblint#77]
This is related to https://github.com/rowanmanning/joblint/issues/26 but the question wasn't answered in that thread.

[One notice](https://github.com/rowanmanning/joblint/blob/2d554a1c8b80c39663e808319ec34e3e31dc0475/lib/rule/expectations.js#L36) includes the phrase 'The job sounds competitive and performance-based'. I understand why a competitive environment may not be good, but I don't understand what's meant by "performance-based". Surely this warning isn't suggesting that employers shouldn't reward employees based on their performance?

Thanks!

**Comment by DanielHeath** [comment]
Performance-based environments imply your performance is measured. If you figure out how to measure an engineers performance well, let us know :)

**Comment by gerrywastaken** [comment]
@DanielHeath haha, nice! LOC of course! ;)

**Comment by NickHeiner** [comment]
> Performance-based environments imply your performance is measured.

Yes, it implies that your performance is measured, but to me it does not suggest it's some arbitrary metric, but a holistic evaluation using feedback from a variety of peers and your manager.

**Comment by DanielHeath** [comment]
You mean you get promoted if people like you and not if they don't?

**Comment by NickHeiner** [comment]
> You mean you get promoted if people like you and not if they don't?

Do you honestly think that's what I mean?

I mean that you get promoted if your peers and manager see you as providing value to the business. Is that a perfect system? No. Is is possible to create a review process where you incentivize looking good instead of creating real value? Yes. But is it not desirable to reward the highest achievers? Is there a better way to ensure that those rewards are allocated correctly?

**Comment by rowanmanning** [comment]
I think there's a little misunderstanding as to the original reasoning behind this rule. If you look at the description for that rule (use the `--verbose` flag) then it states:

> Competition can be healthy, but for a lot of people a heavily competitive environment can be a strain. You could also potentially be excluding people who have more important outside-of-work commitments, such as a family.

This message is `notice` level rather than `warning` or `error` so it's not a must-fix if it appears for your job spec. Possibly the "performance-based" part of the message is what's causing confusion, so I'm open to re-wording.

Thanks

**Comment by NickHeiner** [comment]
Yes, the "performance-based" part is what I'm getting hung up on. If that were to be omitted, and it just said, "This job sounds competitive", then I think everything would make more sense.

**Comment by DanielHeath** [comment]
@NickHeiner fair enough.

`Is it not desirable to reward the highest achievers?`: If I can make every project either fail, or look like I was responsible for its success, I'll be the highest achiever. If you have even one person in your organization who will behave that way, the harm done by performance pay will outweigh the good.

For instance, Microsoft introduced Stack Ranking (from 2006 to 2013) to reward their highest achievers. There was some lag, but over the next few years, many of their best engineers quit and their product lines suffered drastically.

**Comment by NickHeiner** [comment]
> If you have even one person in your organization who will behave that way, the harm done by performance pay will outweigh the good.

That completely depends on the size of your organization. But yes, it is possible for employees to behave badly and hurt the overall organization in a wide variety of ways. That's why culture fit interviews are important, and if necessary, those people can be fired.

> For instance, Microsoft introduced Stack Ranking (from 2006 to 2013) to reward their highest achievers. 

I agree that Stack Ranking was problematic, and the fact that Microsoft discontinued it means that even they didn't think it was a good idea after a while. However, Stack Ranking is a specific implementation of the idea that the highest performers should receive the highest compensation, and its failure does not mean that the entire idea is bad. For instance, Stack Ranking insists that each team must fit within a distribution of skill levels; if everyone on a team is performing at a high level, it is impossible to reward them all accordingly. In this case, Stack Ranking is not effectively rewarding high performers for the value they contribute to the company, and so it's understandable that those people would want to leave.

What is the alternative to rewarding according to value created? Giving raises based on tenure at the company? Employee age? (I'm not being facetious; I'm genuinely curious what you think. This could explain some of the difference of opinion we have.)

**Comment by rnalexander** [comment]
@NickHeiner Yes, it is not desirable to try to incentivise people.  I know it sounds weird but there's actually a lot of studies and what it boils down to is that if the job a person is doing requires anything past basic levels of cognition as part of it's work, the classic model of financial incentivising not only doesn't work, but in fact can make people *less* effective.

This video (It's an RSA Animate short) explains it pretty well, with pictures, and I've cued it up to the right place:  https://youtu.be/avnHUxSVfVM?t=36s

**Comment by NickHeiner** [comment]
That's an interesting video. I 100% agree that building an organization purely around financial incentives is not going to be as effective as one that maximizes autonomy, mastery, getting to work on hard problems, and having a purpose. I wish the video had spent a little more time on the part that's directly relevant to your point about how greater rewards make people perform worse.

Anyway, for the purpose of the conversation, let's just say that that's correct, and giving people more money makes them perform worse as software engineers. I would then ask: what alternate model for allocating compensation would you propose? And do you think that Google's success is in spite of its generous compensation?
