### ISSUE TITLE
Rule: Meritocracy (w/ Working Code)

### ISSUE THREAD

**Issue by jmmastey** [rowanmanning/joblint#79]
Thought of this after reading: http://www.garann.com/dev/2012/you-keep-using-that-word/

Related to "performance based" rules, a pretense at meritocracy is possibly a problem. I've created a potential branch that lints / tests correctly for discussion: https://github.com/jmmastey/joblint/tree/meritocracy.

Not 100% satisfied with the verbiage.

**Comment by rowanmanning** [comment]
This looks good, thanks :) I'm currently overhauling Joblint so this might be better to merge after that – new work on the 1.x branch will trip me up. Feel free to open a PR, it won't get merged for a short while but it should eventually
