### ISSUE TITLE
Quote text that triggers error/warning

### ISSUE THREAD

**Issue by meyerweb** [rowanmanning/joblint#80]
It would be helpful to show the text that triggered a given error or warning, ideally with a few words of context.

Use case: I pasted in https://authenticjobs.com/jobs/24888/front-end-web-developer-bristol to test the linter (I have no affiliation with the advertiser; I just picked it at random) and got a “Gender is mentioned” error.  It took me a few reads to realize it was probably because of this paragraph:

> We’re looking for front end developers to join us in our office in central Bristol, developing web tools and apps for huge audiences. Our clients include Google, YouTube, Skype, PayPal and other agencies such as BBH and **Mother**.

_(emphasis added)_

But of course I’m not certain if that’s what did it, because there’s no context given.  Thus this issue.

**Comment by rowanmanning** [comment]
Great idea. I'm overhauling the code-base at the moment and this should be much easier to implement once that's done. I'd like to see this feature added myself :)

**Comment by rowanmanning** [comment]
Hi @meyerweb, this has been added in Joblint 2.0 (in the command-line tool):

<img src="screenshot.png" alt="Joblint output" width="625"/>

I'll work on adding it to the website too, if that's the interface you use. Thanks for reporting :)

**Comment by meyerweb** [comment]
Fantastic.  Thanks, Rowan!
