### ISSUE TITLE
HTTPS on joblint.org

### ISSUE THREAD

**Issue by teolemon** [rowanmanning/joblint#97]
Can you make joblint.org HTTPS compliant using Let's Encrypt ?

**Comment by rowanmanning** [comment]
Hi @teolemon, currently Joblint is hosted on GitHub pages, I'm intending on moving it to somewhere that it's easier to set up HTTPS for as soon as possible. So yep this will happen, just can't really guess at _when_ quite yet

**Comment by rowanmanning** [comment]
Yep this is on my list of things to do! Glad they announced that before I went to the effort of moving the site

**Comment by rowanmanning** [comment]
All done now 👍

**Comment by TheSeg** [comment]
Wonderful! May I also suggest updating the metadata for the website on the repository's main page? The one next to the text description: https://github.com/rowanmanning/joblint/
