### ISSUE TITLE
joblint doesn't get positive discrimination

### ISSUE THREAD

**Issue by anarcat** [rowanmanning/joblint#99]
[this job offer](https://www.koumbit.org/en/content/koumbit-looking-new-member-our-infrastructuresysadmin-team-0) gets flagged in two places, because of it's use of "women" and "men":

```

Use of gendered word (error)

…general, particularly women and those who do…

Replace gendered words with gender-neutral alternatives. Use of gendered words could indicate that you're discriminating in favour of a certain gender.


Use of gendered word (error)

…do not identify as men . We encourage applications…

Replace gendered words with gender-neutral alternatives. Use of gendered words could indicate that you're discriminating in favour of a certain gender.
```

The whole *point* of those phrases is to encourage people from "minorities" or, to quote the full job offer:

> The hiring process for this position will prioritize people who are socially excluded and marginalized from work in system administration, open source, and IT in general, particularly women and those who do not identify as men. We encourage applications from people who are trans, queer, not white, indigenous, disabled, or have precarious immigration status. If you face social discrimination for these reasons or others that you think we should take into account, let us know.

i guess this is similar to #36... but I wonder if this would be a long term goal.

Just matching on keywords will constantly bring up such false positives...

**Comment by topkecleon** [comment]
>The hiring process for this position will prioritize people who are socially excluded and marginalized from work in system administration, open source, and IT in general, particularly women and those who do not identify as men.

Clearly joblint needs to check for illegal practices.

**Comment by noma4i** [comment]
Works as expected. Cater for certain gender is discrimination. Try to avoid that.

**Comment by tponthieux** [comment]
_"The **hiring process for this position will prioritize** people who are socially excluded and **marginalized** from work in system administration, open source, and IT in general, particularly **women** and **those who do not identify as men**. We **encourage** applications from people who are **trans**, **queer**, **not white**, **indigenous**, **disabled**, or have **precarious immigration status**."_


Equal opportunity and equality of outcome are mutually exclusive objectives. This job posting seeks to achieve equality of outcome at the expense of equal opportunity. **Prioritizing candidates** based on **race**, **sex**, **gender identity**, **sexual orientation**, **national origin**, or **citizenship status**, constitutes institutionalized racism and discrimination.

-
-

**U.S. federal law protects individuals from discrimination or harassment based on nine protected classes. Although it is not required by federal law, employer policies may also protect employees from harassment or discrimination based on marital status or sexual orientation.**
- **Race** – Civil Rights Act of 1964
- Religion – Civil Rights Act of 1964
- **National origin** – Civil Rights Act of 1964
- Age (40 and over) – Age Discrimination in Employment Act of 1967
- **Sex** – Equal Pay Act of 1963 and Civil Rights Act of 1964
- The Equal Employment Opportunity Commission interprets 'sex' to include discrimination based on **sexual orientation and gender identity**[2]
- Pregnancy – Pregnancy Discrimination Act
- Familial status – Civil Rights Act of 1968 Title VIII: Prohibits discrimination for having children, with an exception for senior housing. Also prohibits making a preference for those with children.
- **Disability status** – Rehabilitation Act of 1973 and Americans with Disabilities Act of 1990
- Veteran status – Vietnam Era Veterans' Readjustment Assistance Act of 1974 and Uniformed Services Employment and Reemployment Rights Act
- Genetic information – Genetic Information Nondiscrimination Act
